spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/task_crud?allowPublicKeyRetrieval=true&useSSL=false'
    username: root
    password: 1robo1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
